# Coleta manual (busca na web, sem API) · Sorocaba · outubro/2026
# Cada lugar: (nome, tipo, subtipo, {fonte: (nota, avaliações)}, observação)
# Fontes: ta = Tripadvisor (escala 1–5), g = Google (via Wanderlog / Restaurant Guru / guias),
#         fq = Foursquare (convertido de 0–10 para 0–5)
L = []
def add(nome, tipo, sub, fontes, obs=""):
    L.append({"nome": nome, "tipo": tipo, "sub": sub, "fontes": fontes, "obs": obs})

R, B, P, S, E = "Restaurantes", "Bares", "Parques", "Shows e baladas", "Eventos"

# ---- Restaurantes
add("Duo Bistrô", R, "Contemporânea", {"ta": (4.9, 301)})
add("Fior di Zucca Cucina d'Italia", R, "Italiana", {"ta": (4.9, 513)})
add("La Doc Gastronomia", R, "Italiana", {"ta": (4.7, 748)})
add("Donna Florinda Pizzaria Artesanal", R, "Pizzaria", {"ta": (4.7, 659)})
add("Finestra Del Vino", R, "Italiana / vinhos", {"ta": (4.8, 13)})
add("Izumi Culinária Japonesa", R, "Japonesa", {"ta": (4.5, 350), "fq": (4.35, 323)})
add("Yoshi's Japanese Food", R, "Japonesa", {"ta": (4.3, 910)})
add("Quero Cookies", R, "Doceria", {"ta": (4.9, 214)})
add("Coalhada Burger", R, "Hamburgueria", {"ta": (4.7, 28)})
add("DONNA Hamburgueria Artesanal", R, "Hamburgueria", {"ta": (4.7, 45)})
add("Kleine Gasse", R, "Alemã", {"ta": (5.0, 26)})
add("El Tranvia", R, "Parrilla uruguaia", {"g": (4.5, 816)})
add("Hanami Sushi", R, "Japonesa", {"g": (5.0, 294), "ta": (5.0, 4)})
add("Caminhoneta Burger & Co.", R, "Hamburgueria", {"g": (4.6, 259)})
add("Josefina Burgers", R, "Hamburgueria", {"g": (4.5, 130)})
add("La Cantina Dell'italiano", R, "Italiana", {"ta": (4.7, 153)})
add("Rural Pizzeria Napoletana", R, "Pizzaria", {"ta": (4.5, 39)})
add("Pastificio Rosalia", R, "Italiana", {"ta": (4.6, 32)})
add("Cuordicrema", R, "Sorveteria / doces", {"ta": (4.6, 37)})
add("Pizzaria Domani", R, "Pizzaria", {"ta": (4.6, 56)})
add("Pio Montes", R, "Italiana", {"ta": (4.4, 519)})
add("Micheluccio Pizzas", R, "Pizzaria", {"ta": (4.3, 277)})
add("Babbo Pizzaria e Choperia", R, "Pizzaria", {"ta": (4.3, 47)})
add("Aspasia Pizzaria & Choperia", R, "Pizzaria", {"ta": (4.2, 204)})
add("Kostela do Japonês", R, "Churrasco / costela", {"g": (4.6, 3177), "ta": (4.3, 486)})
add("O Laçador Churrascaria", R, "Churrascaria", {"g": (4.5, 3573), "ta": (4.2, 138)})
add("Boi na Brasa", R, "Churrascaria", {"ta": (3.8, 100)})
add("Costela & Cia", R, "Costela", {"ta": (4.4, 91)})
add("Dini's Burger", R, "Hamburgueria", {"ta": (4.5, 190)})
add("Columbia Burguers & Shakes", R, "Hamburgueria", {"ta": (4.1, 479)})
add("Paddock Hamburgueria", R, "Hamburgueria", {"ta": (4.1, 90)})
add("Santa Crema Café", R, "Cafeteria / brunch", {"ta": (4.7, 64)})
add("15 Coffee Company", R, "Cafeteria", {"ta": (4.7, 14)})
add("Café com Gato", R, "Cafeteria", {"ta": (4.5, 165)})
add("Oui!Chocolat", R, "Cafeteria / chocolates", {"ta": (4.5, 40)})
add("Cafe Donuts", R, "Cafeteria", {"ta": (4.7, 44)})
add("Deltaexpresso", R, "Cafeteria", {"g": (4.4, 858)})

# ---- Bares
add("O Botequim da Francisca", B, "Boteco", {"ta": (4.4, 160)})
add("O Bretão Pub", B, "Pub", {"ta": (4.9, 41)})
add("Old Kick Kustom", B, "Bar", {"ta": (4.6, 19)})
add("Jack Pub", B, "Pub / música ao vivo", {"ta": (4.2, 98)})
add("Bar Santiago", B, "Bar", {"ta": (4.2, 26)})
add("Salomé Bar", B, "Bar", {"g": (4.6, 0)}, "nº de avaliações não informado")
add("Bar e Espetaria do Marcos Aurélio", B, "Espetaria", {}, "Restaurant Guru: 105 votos, sem nota")
add("Quintal Bar e Espetaria", B, "Espetaria", {}, "Restaurant Guru: 169 votos, sem nota")
add("L&L Rock Bar", B, "Rock bar", {}, "Restaurant Guru: 156 votos, sem nota")
add("Deck Beach Bar", B, "Bar", {})
add("Container 648", B, "Bar", {})
add("Bar do Giba", B, "Boteco", {})

# ---- Parques
add("Pista de Caminhada do Campolim", P, "Parque linear", {"ta": (4.3, 459)})
add("Parque Natural Chico Mendes", P, "Parque natural", {"ta": (4.3, 42)})
add("Parque da Biquinha", P, "Parque histórico", {"ta": (3.8, 56)})
add("Jardim Botânico Irmãos Villas-Bôas", P, "Jardim botânico", {"ta": (3.7, 0)})
add("Parque Kasato Maru", P, "Parque", {"ta": (None, 39)})

# ---- Eventos / cultura
add("Zoológico Quinzinho de Barros", P, "Zoológico", {"ta": (4.3, 1578)})
add("Catedral Metropolitana de Sorocaba", E, "Patrimônio / igreja", {"ta": (4.5, 361)})
add("Céu Sagrado", E, "Espaço religioso / mirante", {"ta": (4.5, 62)})
add("Sesc Sorocaba", E, "Centro cultural / teatro", {"ta": (4.7, 149)})

# ---- lote 2
add("Salomé Bar Matriz", B, "Bar", {"g": (4.6, 47)})
L[:] = [x for x in L if x["nome"] != "Salomé Bar"]
add("Dos Bacanas Bar", B, "Bar / whisky", {})
add("Gastão Bar", B, "Bar de drinks", {})
add("Bar 2 Zé", B, "Boteco", {})
add("Cervejaria 3 Américas", B, "Cervejaria", {})
add("A Cervejaria", B, "Cervejaria", {"ta": (4.0, 105)})
add("Cervejario", B, "Cervejaria", {"fq": (3.8, 42)})
add("Choperia Cervogia", B, "Choperia", {})
add("Cervejaria Honório", B, "Cervejaria", {})
add("Lapa Bar Carioca", S, "Samba", {})
add("Copacabana Bar", S, "Bar / música ao vivo", {})
add("Edub Two", S, "Balada", {"g": (4.2, 198)})
add("Tayus", S, "Balada sertaneja", {})
add("Woods Sorocaba", S, "Balada sertaneja", {})
add("Kaos Club", S, "Balada", {})
add("Asteroid", S, "Rock / shows", {})
add("Depois Bar", S, "Bar / música ao vivo", {})
add("Restaurante da Fazenda", R, "Brasileira", {}, "Restaurant Guru: topo da lista geral (out/2026)")
add("Restaurante Vecchio Cancian", R, "Italiana", {}, "Restaurant Guru: topo da lista geral (out/2026)")
add("Mana Poke", R, "Poke", {}, "Restaurant Guru: topo da lista geral (out/2026)")
add("Yosugiru Sushi", R, "Japonesa", {"rg": (4.9, 0)})
add("Kaishi Sushi", R, "Japonesa", {"rg": (4.8, 0)})
add("Inazuma Sushi", R, "Japonesa", {"rg": (4.9, 0)})
add("Peixaria Casagrande", R, "Frutos do mar", {"rg": (4.8, 0)})
add("Moqueca Caribe", R, "Frutos do mar", {"rg": (4.9, 0)})
add("Bar do Argentino", R, "Carnes", {"rg": (4.7, 0)})
add("Padaria Real Alto da Boa Vista", R, "Padaria", {}, "Restaurant Guru: mais de 21 mil votos")
# parques e cultura (Tripadvisor)
for x in L:
    if x["nome"] == "Jardim Botânico Irmãos Villas-Bôas": x["fontes"] = {"ta": (3.7, 347)}
    if x["nome"] == "Parque Kasato Maru": x["fontes"] = {"ta": (3.9, 39)}
add("Parque do Paço Municipal", P, "Parque", {"ta": (4.4, 9)})
add("Ciclovia de Sorocaba", P, "Ciclovia", {"ta": (4.1, 246)})
add("Parque da Biodiversidade", P, "Parque", {"ta": (2.7, 16)})
add("Fundec", E, "Teatro / centro cultural", {"ta": (4.6, 135)})
add("Teatro Sesi Sorocaba", E, "Teatro", {"ta": (4.2, 46)})
add("Teatro Municipal Teotônio Vilela", E, "Teatro", {"ta": (4.1, 59)})
add("MACS · Museu de Arte Contemporânea", E, "Museu", {"ta": (4.0, 70)})
add("Museu da Estrada de Ferro Sorocabana", E, "Museu", {"ta": (3.8, 111)})
add("Museu Histórico Sorocabano", E, "Museu", {"ta": (3.7, 71)})
add("Museu da Computação e Informática", E, "Museu", {"ta": (3.8, 17)})
# já no site (para referência)
add("Parque das Águas", P, "Parque urbano", {"ta": (4.3, 119)}, "já no site")
add("Parque da Água Vermelha", P, "Parque natural", {"ta": (4.1, 124)}, "já no site")

# ---- lote 3
def upd(nome, **kw):
    for x in L:
        if x["nome"] == nome:
            for k, v in kw.items():
                if k == "fontes": x["fontes"].update(v)
                else: x[k] = v
            return
    raise KeyError(nome)
upd("Bar do Giba", fontes={"ta": (4.5, 63), "rg": (4.8, 6113)})
upd("Gastão Bar", fontes={"ta": (3.1, 15)})
upd("Dos Bacanas Bar", fontes={"g": (4.5, 1643)})
upd("Lapa Bar Carioca", fontes={"g": (4.6, 218)})
upd("Asteroid", fontes={"g": (4.3, 2168), "ta": (4.0, 6)})
upd("Kaos Club", fontes={"g": (4.2, 213)})
upd("Tayus", fontes={"g": (4.3, 220)}, obs="FECHADO definitivamente (Wanderlog)")
upd("Padaria Real Alto da Boa Vista", fontes={"ta": (4.6, 1202)})
add("Chácara Santa Victória", R, "Brasileira", {"ta": (4.3, 260)})
add("Tammy Pastelaria", R, "Pastelaria", {"ta": (4.3, 240)})
add("Restaurante Da Terra", R, "Brasileira", {"ta": (4.4, 16)})
add("Chico Rosa Bar e Restaurante", R, "Brasileira / bar", {"ta": (4.2, 225)})
add("PaDovaNella", R, "Italiana", {})
add("Galeto Di Paolo", R, "Galeteria", {})
add("Abu Salim", R, "Árabe", {"ta": (4.2, 64)})
add("Delicias das Arabias", R, "Árabe", {"ta": (3.9, 38)})
add("Arriba Muchacho", R, "Mexicana", {"ta": (4.2, 33)})
add("Casa da Frida", R, "Mexicana", {"ta": (4.4, 0)})
add("Veggie Burgers", R, "Vegetariana", {"ta": (4.3, 16)})
add("Restaurante Traíra e Cia", R, "Frutos do mar", {"ta": (3.8, 49)})
add("Helatti Sorvetes Artesanais", R, "Sorveteria", {"ta": (4.6, 69)})
add("Doce Veneno", R, "Doceria", {"ta": (4.6, 173)})
add("Dolomit Gelateria", R, "Sorveteria", {"ta": (4.4, 28)})
add("Doceria Mãos de Fada", R, "Doceria", {"ta": (4.6, 18)})
add("Colombina Dolceria", R, "Doceria", {"ta": (4.2, 102)})
add("Rancho do Cupim", R, "Churrasco", {})
add("Hioki Sushi", R, "Japonesa", {})
add("Bistrô Paulistano", R, "Bistrô", {"ta": (4.6, 0)})

# ---- lote 4
upd("Deck Beach Bar", fontes={"g": (4.1, 924), "ta": (3.0, 50)})
upd("Cervejaria 3 Américas", fontes={"g": (4.4, 875), "ta": (3.7, 30)})
upd("Choperia Cervogia", fontes={"g": (4.6, 555)})
upd("Restaurante Vecchio Cancian", fontes={"g": (4.6, 3784), "ta": (4.0, 80)})
upd("Container 648", obs="sem dados de nota encontrados")
# Parques (lista da prefeitura e guias)
add("Parque dos Espanhóis", P, "Parque", {})
add("Parque Ouro Fino", P, "Parque natural", {})
add("Floresta Nacional de Ipanema (Fazenda Ipanema)", P, "Unidade de conservação / trilhas", {}, "fica em Iperó, divisa com Sorocaba")
add("Parque Maestro Nilson Lombardi", P, "Parque", {})
add("Parque Porto das Águas", P, "Parque", {})
# Cultura
add("Mosteiro de São Bento de Sorocaba", E, "Patrimônio histórico", {})
add("Barracão Cultural", E, "Centro cultural", {})
# Bares (Restaurant Guru: só nº de votos; folha de Sorocaba; wanderlog)
for nome, votos in [("Cervejaria Nobre", 166), ("Barril do Chopp", 144), ("Bar do Bola", 42), ("Bora Bora Beer", 50),
                    ("Naesquina Botequim", 49), ("Bar do Emer", 50), ("Irmãos Molina Chope Bar", 61), ("Raval Bar Sorocaba", 101),
                    ("Bar da Baiana", 96), ("Black Church Pub", 91), ("Capixabas Bar 2", 142), ("Pé Vermeio Bar", 110)]:
    add(nome, B, "Bar", {}, f"Restaurant Guru: top 20 de bares, {votos} votos (sem nota)")
upd("Bar e Espetaria do Marcos Aurélio", obs="Restaurant Guru: 2º no top 20 de bares, 105 votos (sem nota)")
add("Amiiici", B, "Bar de drinks", {}, "Folha de Sorocaba: drinks de bartender vice-campeão World Class 2021")
add("Izakaya Tsuchi", B, "Izakaya", {})
add("Black Pearl Pub", B, "Pub", {})
add("O Beco Bar e Restaurante", B, "Bar", {})
add("Café da Vila", B, "Bar / café", {})
add("Villa Custom Viking Pub", B, "Pub", {})
add("Imperatriz Cervejaria", B, "Cervejaria", {})

# ---- lote 5
upd("Quintal Bar e Espetaria", fontes={"ta": (4.3, 4)})
upd("A Cervejaria", obs="Wanderlog: marcado como FECHADO definitivamente (conferir)")
upd("Capixabas Bar 2", fontes={"g": (4.6, 0)})
upd("Raval Bar Sorocaba", fontes={"g": (4.3, 113)})
upd("L&L Rock Bar", fontes={"ta": (4.3, 367)})
upd("Pé Vermeio Bar", fontes={"ta": (4.8, 8)})
upd("Jack Pub", fontes={"g": (4.5, 3452)})
upd("Amiiici", fontes={"g": (4.5, 230), "ta": (4.9, 24)})
upd("Container 648", fontes={"ta": (5.0, 3)})
upd("Copacabana Bar", fontes={"g": (4.5, 411)})
upd("Depois Bar", fontes={"g": (4.5, 561), "ta": (2.3, 3)})
add("Samboo Bar", S, "Samba / pagode", {})
add("Barboza Bar", S, "Pagode", {})
add("Pub Sorocaba", S, "Música ao vivo / karaokê", {})
add("Black House", S, "Casa de shows", {})
add("Parque Carlos Alberto de Souza (Campolim)", P, "Parque", {}, "mesmo lugar da Pista de Caminhada do Campolim")
L[:] = [x for x in L if x["nome"] != "Parque Carlos Alberto de Souza (Campolim)"]
next(x for x in L if x["nome"] == "Pista de Caminhada do Campolim")["nome"] = "Parque Campolim (Parque Carlos Alberto de Souza)"
